### ISSUE TITLE
RuntimeException: phantm.Main

### ISSUE THREAD

**Issue by jeffery** [colder/phantm#6]
I have managed to compile phantm on Ubuntu precise, but I keep getting the following error when I just execute "./phantm --help"

Exception in thread "main" java.lang.RuntimeException: Cannot figure out how to run target: phantm.Main
        at scala.sys.package$.error(package.scala:27)
        at scala.tools.nsc.GenericRunnerCommand.scala$tools$nsc$GenericRunnerCommand$$guessHowToRun(GenericRunnerCommand.scala:38)
        at scala.tools.nsc.GenericRunnerCommand$$anonfun$2.apply(GenericRunnerCommand.scala:48)
        at scala.tools.nsc.GenericRunnerCommand$$anonfun$2.apply(GenericRunnerCommand.scala:48)
        at scala.Option.getOrElse(Option.scala:108)
        at scala.tools.nsc.GenericRunnerCommand.<init>(GenericRunnerCommand.scala:48)
        at scala.tools.nsc.GenericRunnerCommand.<init>(GenericRunnerCommand.scala:17)
        at scala.tools.nsc.MainGenericRunner.process(MainGenericRunner.scala:33)
        at scala.tools.nsc.MainGenericRunner$.main(MainGenericRunner.scala:89)
        at scala.tools.nsc.MainGenericRunner.main(MainGenericRunner.scala)

Am I missing some configuration?

**Comment by colder** [comment]
Hi,

This error usually indicates either a classpath problem or a partial compilation.

Did you follow the instructions ? If so it might be that they are no longer accurate.

In any case, can you please give me more information on what you did to compile phantm?

Best

**Comment by jeffery** [comment]
sorry false alarm, my target scala version was 2.9.1 instead of 2.9.0 which was hard-coded in the phantom bash script. Thanks for the hard work.

Here is how I went about compiling it on Ubuntu precise.

sudo apt-get update
sudo apt-get install openjdk-6-jdk scala ant

# Install sbt: https://github.com/harrah/xsbt/wiki/Getting-Started-Setup

wget http://apt.typesafe.com/repo-deb-build-0002.deb
sudo dpkg -i repo-deb-build-0002.deb
sudo apt-get update 
sudo apt-get install sbt

wget http://typesafe.artifactoryonline.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch/0.11.3-2/sbt-launch.jar
mkdir -p ~/.sbt/.lib/0.7.4/
mv sbt-launch.jar ~/.sbt/.lib/0.7.4/sbt-launch.jar

git clone git://github.com/colder/phantm.git
cd phantm
make bootstrap
sbt package
